config_translation_example.config:
  title: 'Configuration translation example settings'
  route_name: config_translation_example.config
  description: 'Config translation example settings'
  parent: system.admin_config_system
  weight: 99
