config_translation_example.config:
  path: '/admin/config/config-translation-example/adminsettings'
  defaults:
    _form: '\Drupal\config_translation_example\Form\ConfigForm'
    _title: 'Configuration translation example settings'
  requirements:
    _permission: 'administer site configuration'
